-- =========================================================
-- Seed data Shopee Dataset 2026
-- Sumber: rangkuman "Rincian Biaya Penjual Shopee per Kategori Produk"
-- (Pusat Edukasi Penjual Shopee, update per 25 Februari 2026), dikutip
-- dari artikel pihak ketiga yang menyebutkan sumber resminya.
-- Non-Star & Star/Star+ selalu sama persis (sesuai ketentuan Shopee).
-- Kolom mall_estimasi = 1 menandakan tarif Mall tidak disebutkan eksplisit
-- untuk item tsb di sumber, jadi dipakai tarif Mall terdekat di kelompok
-- yang sama sebagai pendekatan -- SEBAIKNYA DICEK ULANG berkala ke halaman
-- resmi Shopee (seller.shopee.co.id/edu/article/15965) karena tarif bisa berubah.
-- =========================================================

USE kalkulator_shopee;

ALTER TABLE shopee_dataset_2026
    ADD COLUMN IF NOT EXISTS mall_estimasi TINYINT(1) NOT NULL DEFAULT 0
    COMMENT '1 = tarif mall estimasi/pendekatan, bukan disebutkan eksplisit di sumber';

TRUNCATE TABLE shopee_dataset_2026;

INSERT INTO shopee_dataset_2026
    (category, subcategory, product, fee_admin, fee_affiliate, tarif_non_star, tarif_star, tarif_mall, mall_estimasi, slug, keywords)
VALUES
('Fashion', 'Perhiasan', 'Logam Mulia', 4.25, 4.25, 4.25, 4.25, 3.2, 0, 'fashion-perhiasan-logam-mulia', 'Fashion Perhiasan Logam Mulia'),
('Fashion', 'Perhiasan', 'Perhiasan Berharga', 4.25, 4.25, 4.25, 4.25, 3.2, 0, 'fashion-perhiasan-perhiasan-berharga', 'Fashion Perhiasan Perhiasan Berharga'),
('Fashion', 'Perhiasan', 'Perhiasan Bayi & Anak (gelang, anting, kalung, cincin)', 4.25, 4.25, 4.25, 4.25, 7.7, 1, 'fashion-perhiasan-perhiasan-bayi-anak-gelang-anting-kalung-cincin', 'Fashion Perhiasan Perhiasan Bayi & Anak (gelang, anting, kalung, cincin)'),
('Fashion', 'Pakaian', 'Pakaian Pria (atasan, celana, jaket, dll)', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fashion-pakaian-pakaian-pria-atasan-celana-jaket-dll', 'Fashion Pakaian Pakaian Pria (atasan, celana, jaket, dll)'),
('Fashion', 'Pakaian', 'Pakaian Wanita (atasan, dress, rok, dll)', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fashion-pakaian-pakaian-wanita-atasan-dress-rok-dll', 'Fashion Pakaian Pakaian Wanita (atasan, dress, rok, dll)'),
('Fashion', 'Fashion Muslim', 'Mukena', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fashion-fashion-muslim-mukena', 'Fashion Fashion Muslim Mukena'),
('Fashion', 'Fashion Muslim', 'Outerwear Muslim', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fashion-fashion-muslim-outerwear-muslim', 'Fashion Fashion Muslim Outerwear Muslim'),
('Fashion', 'Fashion Muslim', 'Pakaian Muslim Pria/Wanita/Anak', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fashion-fashion-muslim-pakaian-muslim-pria-wanita-anak', 'Fashion Fashion Muslim Pakaian Muslim Pria/Wanita/Anak'),
('Fashion', 'Fashion Muslim', 'Set Perlengkapan Sholat', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fashion-fashion-muslim-set-perlengkapan-sholat', 'Fashion Fashion Muslim Set Perlengkapan Sholat'),
('Fashion', 'Aksesoris Tambahan', 'Masker', 8.25, 8.25, 8.25, 8.25, 10.45, 0, 'fashion-aksesoris-tambahan-masker', 'Fashion Aksesoris Tambahan Masker'),
('Fashion', 'Aksesoris Fashion', 'Anting', 9, 9, 9, 9, 7.7, 0, 'fashion-aksesoris-fashion-anting', 'Fashion Aksesoris Fashion Anting'),
('Fashion', 'Aksesoris Fashion', 'Cincin', 9, 9, 9, 9, 7.7, 0, 'fashion-aksesoris-fashion-cincin', 'Fashion Aksesoris Fashion Cincin'),
('Fashion', 'Aksesoris Fashion', 'Gelang', 9, 9, 9, 9, 7.7, 0, 'fashion-aksesoris-fashion-gelang', 'Fashion Aksesoris Fashion Gelang'),
('Fashion', 'Aksesoris Fashion', 'Kalung', 9, 9, 9, 9, 7.7, 0, 'fashion-aksesoris-fashion-kalung', 'Fashion Aksesoris Fashion Kalung'),
('Fashion', 'Aksesoris Fashion', 'Set Aksesoris', 9, 9, 9, 9, 7.7, 0, 'fashion-aksesoris-fashion-set-aksesoris', 'Fashion Aksesoris Fashion Set Aksesoris'),
('Fashion', 'Aksesoris Fashion', 'Aksesoris Rambut', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-aksesoris-rambut', 'Fashion Aksesoris Fashion Aksesoris Rambut'),
('Fashion', 'Aksesoris Fashion', 'Dasi', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-dasi', 'Fashion Aksesoris Fashion Dasi'),
('Fashion', 'Aksesoris Fashion', 'Ikat Pinggang', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-ikat-pinggang', 'Fashion Aksesoris Fashion Ikat Pinggang'),
('Fashion', 'Aksesoris Fashion', 'Kacamata', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-kacamata', 'Fashion Aksesoris Fashion Kacamata'),
('Fashion', 'Aksesoris Fashion', 'Syal', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-syal', 'Fashion Aksesoris Fashion Syal'),
('Fashion', 'Aksesoris Fashion', 'Topi', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-topi', 'Fashion Aksesoris Fashion Topi'),
('Fashion', 'Aksesoris Fashion', 'Kaos Kaki (aksesoris)', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-kaos-kaki-aksesoris', 'Fashion Aksesoris Fashion Kaos Kaki (aksesoris)'),
('Fashion', 'Jam Tangan', 'Jam Tangan', 9, 9, 9, 9, 10.2, 0, 'fashion-jam-tangan-jam-tangan', 'Fashion Jam Tangan Jam Tangan'),
('Fashion', 'Sepatu', 'Sepatu Pria', 9, 9, 9, 9, 10.2, 0, 'fashion-sepatu-sepatu-pria', 'Fashion Sepatu Sepatu Pria'),
('Fashion', 'Sepatu', 'Sepatu Wanita', 9, 9, 9, 9, 10.2, 0, 'fashion-sepatu-sepatu-wanita', 'Fashion Sepatu Sepatu Wanita'),
('Fashion', 'Tas', 'Tas Pria', 9, 9, 9, 9, 10.2, 0, 'fashion-tas-tas-pria', 'Fashion Tas Tas Pria'),
('Fashion', 'Tas', 'Tas Wanita', 9, 9, 9, 9, 10.2, 0, 'fashion-tas-tas-wanita', 'Fashion Tas Tas Wanita'),
('Fashion', 'Koper & Tas Travel', 'Koper & Tas Travel', 9, 9, 9, 9, 10.2, 0, 'fashion-koper-tas-travel-koper-tas-travel', 'Fashion Koper & Tas Travel Koper & Tas Travel'),
('Fashion', 'Fashion Bayi & Anak', 'Pakaian Bayi & Anak', 9, 9, 9, 9, 10.2, 0, 'fashion-fashion-bayi-anak-pakaian-bayi-anak', 'Fashion Fashion Bayi & Anak Pakaian Bayi & Anak'),
('Fashion', 'Fashion Bayi & Anak', 'Sepatu Bayi & Anak', 9, 9, 9, 9, 10.2, 0, 'fashion-fashion-bayi-anak-sepatu-bayi-anak', 'Fashion Fashion Bayi & Anak Sepatu Bayi & Anak'),
('Fashion', 'Fashion Bayi & Anak', 'Tas Bayi & Anak', 9, 9, 9, 9, 10.2, 0, 'fashion-fashion-bayi-anak-tas-bayi-anak', 'Fashion Fashion Bayi & Anak Tas Bayi & Anak'),
('Fashion', 'Aksesoris Fashion', 'Stocking', 9, 9, 9, 9, 10.2, 0, 'fashion-aksesoris-fashion-stocking', 'Fashion Aksesoris Fashion Stocking'),
('Fashion', 'Kaos Kaki', 'Kaos Kaki Pria & Wanita', 10, 10, 10, 10, 11.7, 1, 'fashion-kaos-kaki-kaos-kaki-pria-wanita', 'Fashion Kaos Kaki Kaos Kaki Pria & Wanita'),
('Fashion', 'Fashion Muslim', 'Baju Olahraga Muslim', 10, 10, 10, 10, 11.7, 0, 'fashion-fashion-muslim-baju-olahraga-muslim', 'Fashion Fashion Muslim Baju Olahraga Muslim'),
('Fashion', 'Fashion Muslim', 'Baju Renang Muslim', 10, 10, 10, 10, 11.7, 0, 'fashion-fashion-muslim-baju-renang-muslim', 'Fashion Fashion Muslim Baju Renang Muslim'),
('Fashion', 'Tas', 'Tas Duffel', 10, 10, 10, 10, 11.7, 0, 'fashion-tas-tas-duffel', 'Fashion Tas Tas Duffel'),
('FMCG', 'Bahan Makanan', 'Telur', 6.5, 6.5, 6.5, 6.5, 6.2, 0, 'fmcg-bahan-makanan-telur', 'FMCG Bahan Makanan Telur'),
('FMCG', 'Ibu & Bayi', 'Vitamin & Suplemen Bayi', 6.5, 6.5, 6.5, 6.5, 7.2, 1, 'fmcg-ibu-bayi-vitamin-suplemen-bayi', 'FMCG Ibu & Bayi Vitamin & Suplemen Bayi'),
('FMCG', 'Ibu & Bayi', 'Susu Formula & Makanan Bayi', 6.75, 6.75, 6.75, 6.75, 7.7, 0, 'fmcg-ibu-bayi-susu-formula-makanan-bayi', 'FMCG Ibu & Bayi Susu Formula & Makanan Bayi'),
('FMCG', 'Bahan Makanan', 'Bahan Baking', 6.75, 6.75, 6.75, 6.75, 6.2, 0, 'fmcg-bahan-makanan-bahan-baking', 'FMCG Bahan Makanan Bahan Baking'),
('FMCG', 'Bahan Makanan', 'Bahan Pokok (beras, mie, pasta, biji-bijian, seafood kering)', 6.75, 6.75, 6.75, 6.75, 6.2, 0, 'fmcg-bahan-makanan-bahan-pokok-beras-mie-pasta-biji-bijian-seafood-kering', 'FMCG Bahan Makanan Bahan Pokok (beras, mie, pasta, biji-bijian, seafood kering)'),
('FMCG', 'Bahan Makanan', 'Kebutuhan Memasak', 6.75, 6.75, 6.75, 6.75, 6.2, 0, 'fmcg-bahan-makanan-kebutuhan-memasak', 'FMCG Bahan Makanan Kebutuhan Memasak'),
('FMCG', 'Bahan Makanan', 'Makanan Segar & Beku', 6.75, 6.75, 6.75, 6.75, 9.95, 1, 'fmcg-bahan-makanan-makanan-segar-beku', 'FMCG Bahan Makanan Makanan Segar & Beku'),
('FMCG', 'Bahan Makanan', 'Menu Sarapan', 6.75, 6.75, 6.75, 6.75, 10.2, 1, 'fmcg-bahan-makanan-menu-sarapan', 'FMCG Bahan Makanan Menu Sarapan'),
('FMCG', 'Bahan Makanan', 'Es Krim', 6.75, 6.75, 6.75, 6.75, 9.95, 0, 'fmcg-bahan-makanan-es-krim', 'FMCG Bahan Makanan Es Krim'),
('FMCG', 'Ibu & Bayi', 'Kamar Bayi', 8.25, 8.25, 8.25, 8.25, 10.2, 1, 'fmcg-ibu-bayi-kamar-bayi', 'FMCG Ibu & Bayi Kamar Bayi'),
('FMCG', 'Ibu & Bayi', 'Kesehatan Bayi', 8.25, 8.25, 8.25, 8.25, 7.2, 0, 'fmcg-ibu-bayi-kesehatan-bayi', 'FMCG Ibu & Bayi Kesehatan Bayi'),
('FMCG', 'Ibu & Bayi', 'Perlengkapan Mandi Bayi', 8.25, 8.25, 8.25, 8.25, 7.2, 0, 'fmcg-ibu-bayi-perlengkapan-mandi-bayi', 'FMCG Ibu & Bayi Perlengkapan Mandi Bayi'),
('FMCG', 'Ibu & Bayi', 'Mainan Umum', 8.25, 8.25, 8.25, 8.25, 10.2, 1, 'fmcg-ibu-bayi-mainan-umum', 'FMCG Ibu & Bayi Mainan Umum'),
('FMCG', 'Ibu & Bayi', 'Set Hadiah Bayi', 8.25, 8.25, 8.25, 8.25, 9.95, 1, 'fmcg-ibu-bayi-set-hadiah-bayi', 'FMCG Ibu & Bayi Set Hadiah Bayi'),
('FMCG', 'Perawatan & Kecantikan', 'Susu & Olahan (umum)', 8.25, 8.25, 8.25, 8.25, 10.2, 1, 'fmcg-perawatan-kecantikan-susu-olahan-umum', 'FMCG Perawatan & Kecantikan Susu & Olahan (umum)'),
('FMCG', 'Perawatan & Kecantikan', 'Kosmetik', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fmcg-perawatan-kecantikan-kosmetik', 'FMCG Perawatan & Kecantikan Kosmetik'),
('FMCG', 'Perawatan & Kecantikan', 'Skincare', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fmcg-perawatan-kecantikan-skincare', 'FMCG Perawatan & Kecantikan Skincare'),
('FMCG', 'Perawatan & Kecantikan', 'Parfum', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fmcg-perawatan-kecantikan-parfum', 'FMCG Perawatan & Kecantikan Parfum'),
('FMCG', 'Perawatan & Kecantikan', 'Perawatan Rambut & Tubuh', 8.25, 8.25, 8.25, 8.25, 9.95, 0, 'fmcg-perawatan-kecantikan-perawatan-rambut-tubuh', 'FMCG Perawatan & Kecantikan Perawatan Rambut & Tubuh'),
('FMCG', 'Ibu & Bayi', 'Popok & Pispot', 9, 9, 9, 9, 7.2, 0, 'fmcg-ibu-bayi-popok-pispot', 'FMCG Ibu & Bayi Popok & Pispot'),
('FMCG', 'Kesehatan', 'Kesehatan Seksual', 9, 9, 9, 9, 7.7, 0, 'fmcg-kesehatan-kesehatan-seksual', 'FMCG Kesehatan Kesehatan Seksual'),
('FMCG', 'Kesehatan', 'Obat & Alat Kesehatan (alat ukur tekanan/gula darah, dll)', 9, 9, 9, 9, 7.7, 0, 'fmcg-kesehatan-obat-alat-kesehatan-alat-ukur-tekanan-gula-darah-dll', 'FMCG Kesehatan Obat & Alat Kesehatan (alat ukur tekanan/gula darah, dll)'),
('FMCG', 'Perawatan Diri', 'Sikat Gigi & Pasta Gigi', 9, 9, 9, 9, 7.2, 0, 'fmcg-perawatan-diri-sikat-gigi-pasta-gigi', 'FMCG Perawatan Diri Sikat Gigi & Pasta Gigi'),
('FMCG', 'Perawatan Diri', 'Pembalut', 9, 9, 9, 9, 9.95, 0, 'fmcg-perawatan-diri-pembalut', 'FMCG Perawatan Diri Pembalut'),
('FMCG', 'Kesehatan', 'Suplemen Makanan', 9, 9, 9, 9, 7.2, 0, 'fmcg-kesehatan-suplemen-makanan', 'FMCG Kesehatan Suplemen Makanan'),
('FMCG', 'Bahan Makanan', 'Makanan Instan', 9, 9, 9, 9, 7.2, 0, 'fmcg-bahan-makanan-makanan-instan', 'FMCG Bahan Makanan Makanan Instan'),
('FMCG', 'Bahan Makanan', 'Roti & Kue', 9, 9, 9, 9, 10.2, 0, 'fmcg-bahan-makanan-roti-kue', 'FMCG Bahan Makanan Roti & Kue'),
('FMCG', 'Ibu & Bayi', 'Keamanan Bayi', 9.5, 9.5, 9.5, 9.5, 10.2, 1, 'fmcg-ibu-bayi-keamanan-bayi', 'FMCG Ibu & Bayi Keamanan Bayi'),
('FMCG', 'Ibu & Bayi', 'Kesehatan Kehamilan', 9.5, 9.5, 9.5, 9.5, 10.2, 1, 'fmcg-ibu-bayi-kesehatan-kehamilan', 'FMCG Ibu & Bayi Kesehatan Kehamilan'),
('FMCG', 'Ibu & Bayi', 'Pompa ASI', 9.5, 9.5, 9.5, 9.5, 10.2, 1, 'fmcg-ibu-bayi-pompa-asi', 'FMCG Ibu & Bayi Pompa ASI'),
('FMCG', 'Ibu & Bayi', 'Perlengkapan Travelling Bayi', 9.5, 9.5, 9.5, 9.5, 10.2, 1, 'fmcg-ibu-bayi-perlengkapan-travelling-bayi', 'FMCG Ibu & Bayi Perlengkapan Travelling Bayi'),
('FMCG', 'Kesehatan', 'Obat OTC & Obat Tradisional', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'fmcg-kesehatan-obat-otc-obat-tradisional', 'FMCG Kesehatan Obat OTC & Obat Tradisional'),
('FMCG', 'Makanan Ringan', 'Permen', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-makanan-ringan-permen', 'FMCG Makanan Ringan Permen'),
('FMCG', 'Makanan Ringan', 'Cokelat', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-makanan-ringan-cokelat', 'FMCG Makanan Ringan Cokelat'),
('FMCG', 'Makanan Ringan', 'Biskuit', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-makanan-ringan-biskuit', 'FMCG Makanan Ringan Biskuit'),
('FMCG', 'Makanan Ringan', 'Keripik', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-makanan-ringan-keripik', 'FMCG Makanan Ringan Keripik'),
('FMCG', 'Bahan Makanan', 'Bahan Pokok Kaleng', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-bahan-makanan-bahan-pokok-kaleng', 'FMCG Bahan Makanan Bahan Pokok Kaleng'),
('FMCG', 'Minuman', 'Minuman', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-minuman-minuman', 'FMCG Minuman Minuman'),
('FMCG', 'Minuman', 'Minuman Alkohol', 9.5, 9.5, 9.5, 9.5, 10.2, 1, 'fmcg-minuman-minuman-alkohol', 'FMCG Minuman Minuman Alkohol'),
('FMCG', 'Set Hadiah', 'Set Hadiah & Hampers', 9.5, 9.5, 9.5, 9.5, 10.2, 0, 'fmcg-set-hadiah-set-hadiah-hampers', 'FMCG Set Hadiah Set Hadiah & Hampers'),
('FMCG', 'Mainan', 'Mainan Inflatable & Perosotan', 10, 10, 10, 10, 11.7, 0, 'fmcg-mainan-mainan-inflatable-perosotan', 'FMCG Mainan Mainan Inflatable & Perosotan'),
('FMCG', 'Perawatan Diri', 'Hand Sanitizer', 10, 10, 10, 10, 10.2, 0, 'fmcg-perawatan-diri-hand-sanitizer', 'FMCG Perawatan Diri Hand Sanitizer'),
('Elektronik', 'Handphone & Tablet', 'Handphone', 5.25, 5.25, 5.25, 5.25, 4.7, 0, 'elektronik-handphone-tablet-handphone', 'Elektronik Handphone & Tablet Handphone'),
('Elektronik', 'Handphone & Tablet', 'Tablet', 5.25, 5.25, 5.25, 5.25, 4.7, 0, 'elektronik-handphone-tablet-tablet', 'Elektronik Handphone & Tablet Tablet'),
('Elektronik', 'Handphone & Tablet', 'Proyektor & Aksesoris', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-handphone-tablet-proyektor-aksesoris', 'Elektronik Handphone & Tablet Proyektor & Aksesoris'),
('Elektronik', 'Komputer', 'Desktop', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-desktop', 'Elektronik Komputer Desktop'),
('Elektronik', 'Komputer', 'Komponen Desktop & Laptop', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-komponen-desktop-laptop', 'Elektronik Komputer Komponen Desktop & Laptop'),
('Elektronik', 'Komputer', 'Laptop', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-laptop', 'Elektronik Komputer Laptop'),
('Elektronik', 'Komputer', 'Monitor', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-monitor', 'Elektronik Komputer Monitor'),
('Elektronik', 'Komputer', 'Penyimpanan Data', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-penyimpanan-data', 'Elektronik Komputer Penyimpanan Data'),
('Elektronik', 'Komputer', 'Printer & Scanner', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-printer-scanner', 'Elektronik Komputer Printer & Scanner'),
('Elektronik', 'Komputer', 'Peralatan Kantor', 5.25, 5.25, 5.25, 5.25, 4.2, 0, 'elektronik-komputer-peralatan-kantor', 'Elektronik Komputer Peralatan Kantor'),
('Elektronik', 'Alat Rumah Tangga', 'Mesin Cuci', 6.5, 6.5, 6.5, 6.5, 7.2, 1, 'elektronik-alat-rumah-tangga-mesin-cuci', 'Elektronik Alat Rumah Tangga Mesin Cuci'),
('Elektronik', 'Alat Rumah Tangga', 'AC', 6.5, 6.5, 6.5, 6.5, 7.2, 1, 'elektronik-alat-rumah-tangga-ac', 'Elektronik Alat Rumah Tangga AC'),
('Elektronik', 'Alat Rumah Tangga', 'Kipas Angin', 6.5, 6.5, 6.5, 6.5, 7.2, 1, 'elektronik-alat-rumah-tangga-kipas-angin', 'Elektronik Alat Rumah Tangga Kipas Angin'),
('Elektronik', 'Dapur', 'Perangkat Dapur', 6.5, 6.5, 6.5, 6.5, 7.2, 0, 'elektronik-dapur-perangkat-dapur', 'Elektronik Dapur Perangkat Dapur'),
('Elektronik', 'TV & Audio', 'TV & Aksesoris', 6.5, 6.5, 6.5, 6.5, 7.2, 0, 'elektronik-tv-audio-tv-aksesoris', 'Elektronik TV & Audio TV & Aksesoris'),
('Elektronik', 'Kamera', 'Kamera & Lensa & Drone', 6.5, 6.5, 6.5, 6.5, 7.7, 1, 'elektronik-kamera-kamera-lensa-drone', 'Elektronik Kamera Kamera & Lensa & Drone'),
('Elektronik', 'Audio', 'Sound Card', 6.5, 6.5, 6.5, 6.5, 4.7, 1, 'elektronik-audio-sound-card', 'Elektronik Audio Sound Card'),
('Elektronik', 'Audio', 'Earphone/Headphone/Headset', 6.75, 6.75, 6.75, 6.75, 7.2, 0, 'elektronik-audio-earphone-headphone-headset', 'Elektronik Audio Earphone/Headphone/Headset'),
('Elektronik', 'Handphone & Tablet', 'Aksesoris HP (modem, USB)', 6.75, 6.75, 6.75, 6.75, 7.2, 0, 'elektronik-handphone-tablet-aksesoris-hp-modem-usb', 'Elektronik Handphone & Tablet Aksesoris HP (modem, USB)'),
('Elektronik', 'Komputer', 'Aksesoris Desktop & Laptop', 6.75, 6.75, 6.75, 6.75, 10.2, 1, 'elektronik-komputer-aksesoris-desktop-laptop', 'Elektronik Komputer Aksesoris Desktop & Laptop'),
('Elektronik', 'Komputer', 'Keyboard & Mouse', 6.75, 6.75, 6.75, 6.75, 7.2, 0, 'elektronik-komputer-keyboard-mouse', 'Elektronik Komputer Keyboard & Mouse'),
('Elektronik', 'Jaringan', 'Komponen Network', 6.75, 6.75, 6.75, 6.75, 7.7, 1, 'elektronik-jaringan-komponen-network', 'Elektronik Jaringan Komponen Network'),
('Elektronik', 'Komputer', 'Software', 6.75, 6.75, 6.75, 6.75, 10.2, 0, 'elektronik-komputer-software', 'Elektronik Komputer Software'),
('Elektronik', 'Audio', 'Amplifier & Mixer', 9, 9, 9, 9, 7.2, 1, 'elektronik-audio-amplifier-mixer', 'Elektronik Audio Amplifier & Mixer'),
('Elektronik', 'Audio', 'Mikrofon', 9, 9, 9, 9, 7.2, 1, 'elektronik-audio-mikrofon', 'Elektronik Audio Mikrofon'),
('Elektronik', 'Audio', 'Perangkat Audio & Speaker', 9, 9, 9, 9, 7.2, 0, 'elektronik-audio-perangkat-audio-speaker', 'Elektronik Audio Perangkat Audio & Speaker'),
('Elektronik', 'Alat Rumah Tangga', 'Peralatan Listrik (remot, telepon)', 9, 9, 9, 9, 7.2, 1, 'elektronik-alat-rumah-tangga-peralatan-listrik-remot-telepon', 'Elektronik Alat Rumah Tangga Peralatan Listrik (remot, telepon)'),
('Elektronik', 'Lainnya', 'Rokok Elektronik', 9, 9, 9, 9, 7.2, 0, 'elektronik-lainnya-rokok-elektronik', 'Elektronik Lainnya Rokok Elektronik'),
('Elektronik', 'Gaming', 'Aksesoris Konsol', 9, 9, 9, 9, 7.2, 0, 'elektronik-gaming-aksesoris-konsol', 'Elektronik Gaming Aksesoris Konsol'),
('Elektronik', 'Handphone & Tablet', 'Kartu Perdana', 9, 9, 9, 9, 7.2, 1, 'elektronik-handphone-tablet-kartu-perdana', 'Elektronik Handphone & Tablet Kartu Perdana'),
('Elektronik', 'Lainnya', 'Walkie Talkie', 9, 9, 9, 9, 9.5, 1, 'elektronik-lainnya-walkie-talkie', 'Elektronik Lainnya Walkie Talkie'),
('Elektronik', 'Audio', 'Media Player', 9.5, 9.5, 9.5, 9.5, 7.7, 1, 'elektronik-audio-media-player', 'Elektronik Audio Media Player'),
('Elektronik', 'Alat Rumah Tangga', 'Baterai', 9.5, 9.5, 9.5, 9.5, 7.7, 1, 'elektronik-alat-rumah-tangga-baterai', 'Elektronik Alat Rumah Tangga Baterai'),
('Elektronik', 'Alat Rumah Tangga', 'Water Heater', 9.5, 9.5, 9.5, 9.5, 7.7, 1, 'elektronik-alat-rumah-tangga-water-heater', 'Elektronik Alat Rumah Tangga Water Heater'),
('Elektronik', 'Gaming', 'Konsol & Video Game', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'elektronik-gaming-konsol-video-game', 'Elektronik Gaming Konsol & Video Game'),
('Elektronik', 'Wearable', 'Smartwatch', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'elektronik-wearable-smartwatch', 'Elektronik Wearable Smartwatch'),
('Elektronik', 'Kamera', 'Kamera Keamanan/CCTV', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'elektronik-kamera-kamera-keamanan-cctv', 'Elektronik Kamera Kamera Keamanan/CCTV'),
('Elektronik', 'Kamera', 'Aksesoris Kamera (tripod, gimbal, lighting)', 9.5, 9.5, 9.5, 9.5, 10.2, 1, 'elektronik-kamera-aksesoris-kamera-tripod-gimbal-lighting', 'Elektronik Kamera Aksesoris Kamera (tripod, gimbal, lighting)'),
('Elektronik', 'Audio', 'Kabel & Konverter Audio/Video', 9.5, 9.5, 9.5, 9.5, 9.95, 1, 'elektronik-audio-kabel-konverter-audio-video', 'Elektronik Audio Kabel & Konverter Audio/Video'),
('Elektronik', 'Wearable', 'Perangkat Wearable (GPS)', 9.5, 9.5, 9.5, 9.5, 9.95, 0, 'elektronik-wearable-perangkat-wearable-gps', 'Elektronik Wearable Perangkat Wearable (GPS)'),
('Elektronik', 'Alat Rumah Tangga', 'Kelistrikan', 10, 10, 10, 10, 10.2, 0, 'elektronik-alat-rumah-tangga-kelistrikan', 'Elektronik Alat Rumah Tangga Kelistrikan'),
('Elektronik', 'Handphone & Tablet', 'Aksesoris HP (casing, charger, tongsis, dll)', 10, 10, 10, 10, 10.2, 0, 'elektronik-handphone-tablet-aksesoris-hp-casing-charger-tongsis-dll', 'Elektronik Handphone & Tablet Aksesoris HP (casing, charger, tongsis, dll)'),
('Lifestyle', 'Kendaraan', 'Mobil (unit)', 2.5, 2.5, 2.5, 2.5, 2.5, 0, 'lifestyle-kendaraan-mobil-unit', 'Lifestyle Kendaraan Mobil (unit)'),
('Lifestyle', 'Kendaraan', 'Sepeda Motor (unit)', 2.5, 2.5, 2.5, 2.5, 2.5, 0, 'lifestyle-kendaraan-sepeda-motor-unit', 'Lifestyle Kendaraan Sepeda Motor (unit)'),
('Lifestyle', 'Dapur', 'Sealer', 6.5, 6.5, 6.5, 6.5, 7.2, 1, 'lifestyle-dapur-sealer', 'Lifestyle Dapur Sealer'),
('Lifestyle', 'Otomotif', 'Aksesoris & Suku Cadang Mobil (eksterior/interior/perawatan)', 8.25, 8.25, 8.25, 8.25, 10.45, 1, 'lifestyle-otomotif-aksesoris-suku-cadang-mobil-eksterior-interior-perawatan', 'Lifestyle Otomotif Aksesoris & Suku Cadang Mobil (eksterior/interior/perawatan)'),
('Lifestyle', 'Otomotif', 'Aksesoris Motor', 8.25, 8.25, 8.25, 8.25, 10.45, 1, 'lifestyle-otomotif-aksesoris-motor', 'Lifestyle Otomotif Aksesoris Motor'),
('Lifestyle', 'Otomotif', 'Helm', 8.25, 8.25, 8.25, 8.25, 10.45, 1, 'lifestyle-otomotif-helm', 'Lifestyle Otomotif Helm'),
('Lifestyle', 'Otomotif', 'Suku Cadang Motor', 8.25, 8.25, 8.25, 8.25, 10.45, 0, 'lifestyle-otomotif-suku-cadang-motor', 'Lifestyle Otomotif Suku Cadang Motor'),
('Lifestyle', 'Buku', 'Buku Bayi', 8.25, 8.25, 8.25, 8.25, 7.7, 1, 'lifestyle-buku-buku-bayi', 'Lifestyle Buku Buku Bayi'),
('Lifestyle', 'Olahraga & Outdoor', 'Jas Hujan (olahraga)', 8.25, 8.25, 8.25, 8.25, 10.45, 1, 'lifestyle-olahraga-outdoor-jas-hujan-olahraga', 'Lifestyle Olahraga & Outdoor Jas Hujan (olahraga)'),
('Lifestyle', 'Alat Tulis', 'Alat Tulis', 9, 9, 9, 9, 7.2, 0, 'lifestyle-alat-tulis-alat-tulis', 'Lifestyle Alat Tulis Alat Tulis'),
('Lifestyle', 'Alat Tulis', 'Buku Tulis & Kertas', 9, 9, 9, 9, 7.2, 0, 'lifestyle-alat-tulis-buku-tulis-kertas', 'Lifestyle Alat Tulis Buku Tulis & Kertas'),
('Lifestyle', 'Alat Tulis', 'Surat-Menyurat', 9, 9, 9, 9, 7.2, 0, 'lifestyle-alat-tulis-surat-menyurat', 'Lifestyle Alat Tulis Surat-Menyurat'),
('Lifestyle', 'Buku', 'Buku Bacaan', 9, 9, 9, 9, 7.7, 1, 'lifestyle-buku-buku-bacaan', 'Lifestyle Buku Buku Bacaan'),
('Lifestyle', 'Buku', 'E-Book', 9, 9, 9, 9, 7.2, 0, 'lifestyle-buku-e-book', 'Lifestyle Buku E-Book'),
('Lifestyle', 'Otomotif', 'Oli & Pelumas Kendaraan', 9, 9, 9, 9, 10.45, 0, 'lifestyle-otomotif-oli-pelumas-kendaraan', 'Lifestyle Otomotif Oli & Pelumas Kendaraan'),
('Lifestyle', 'Hadiah', 'Souvenir & Hadiah', 9, 9, 9, 9, 10.45, 1, 'lifestyle-hadiah-souvenir-hadiah', 'Lifestyle Hadiah Souvenir & Hadiah'),
('Lifestyle', 'Perlengkapan Rumah', 'Lampu', 9, 9, 9, 9, 7.7, 1, 'lifestyle-perlengkapan-rumah-lampu', 'Lifestyle Perlengkapan Rumah Lampu'),
('Lifestyle', 'Perlengkapan Rumah', 'Bunga', 9, 9, 9, 9, 10.45, 1, 'lifestyle-perlengkapan-rumah-bunga', 'Lifestyle Perlengkapan Rumah Bunga'),
('Lifestyle', 'Perlengkapan Rumah', 'Kursi & Bangku', 9, 9, 9, 9, 7.2, 0, 'lifestyle-perlengkapan-rumah-kursi-bangku', 'Lifestyle Perlengkapan Rumah Kursi & Bangku'),
('Lifestyle', 'Perlengkapan Rumah', 'Perawatan Rumah (tisu, pembersih, detergen)', 9, 9, 9, 9, 11.7, 1, 'lifestyle-perlengkapan-rumah-perawatan-rumah-tisu-pembersih-detergen', 'Lifestyle Perlengkapan Rumah Perawatan Rumah (tisu, pembersih, detergen)'),
('Lifestyle', 'Perlengkapan Rumah', 'Perlengkapan Pesta', 9, 9, 9, 9, 10.45, 1, 'lifestyle-perlengkapan-rumah-perlengkapan-pesta', 'Lifestyle Perlengkapan Rumah Perlengkapan Pesta'),
('Lifestyle', 'Alat Tulis', 'Perlengkapan Sekolah & Kantor', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'lifestyle-alat-tulis-perlengkapan-sekolah-kantor', 'Lifestyle Alat Tulis Perlengkapan Sekolah & Kantor'),
('Lifestyle', 'Alat Tulis', 'Bubble Wrap', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'lifestyle-alat-tulis-bubble-wrap', 'Lifestyle Alat Tulis Bubble Wrap'),
('Lifestyle', 'Buku', 'Buku Bacaan (komik/audio)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'lifestyle-buku-buku-bacaan-komik-audio', 'Lifestyle Buku Buku Bacaan (komik/audio)'),
('Lifestyle', 'Buku', 'Majalah & Koran', 9.5, 9.5, 9.5, 9.5, 11.7, 1, 'lifestyle-buku-majalah-koran', 'Lifestyle Buku Majalah & Koran'),
('Lifestyle', 'Hewan Peliharaan', 'Hewan Peliharaan (semua)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'lifestyle-hewan-peliharaan-hewan-peliharaan-semua', 'Lifestyle Hewan Peliharaan Hewan Peliharaan (semua)'),
('Lifestyle', 'Hobi & Koleksi', 'Hobi & Koleksi (musik, koleksi, games)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'lifestyle-hobi-koleksi-hobi-koleksi-musik-koleksi-games', 'Lifestyle Hobi & Koleksi Hobi & Koleksi (musik, koleksi, games)'),
('Lifestyle', 'Otomotif', 'Suku Cadang Mobil', 9.5, 9.5, 9.5, 9.5, 10.45, 1, 'lifestyle-otomotif-suku-cadang-mobil', 'Lifestyle Otomotif Suku Cadang Mobil'),
('Lifestyle', 'Perlengkapan Rumah', 'Lampu (perlengkapan rumah)', 9.5, 9.5, 9.5, 9.5, 7.7, 1, 'lifestyle-perlengkapan-rumah-lampu-perlengkapan-rumah', 'Lifestyle Perlengkapan Rumah Lampu (perlengkapan rumah)'),
('Lifestyle', 'Buku', 'Art Paper', 9.5, 9.5, 9.5, 9.5, 9.95, 1, 'lifestyle-buku-art-paper', 'Lifestyle Buku Art Paper'),
('Lifestyle', 'Alat Tulis', 'Perlengkapan Menggambar', 10, 10, 10, 10, 11.7, 0, 'lifestyle-alat-tulis-perlengkapan-menggambar', 'Lifestyle Alat Tulis Perlengkapan Menggambar'),
('Lifestyle', 'Buku', 'Majalah & Koran (cetak)', 10, 10, 10, 10, 11.7, 0, 'lifestyle-buku-majalah-koran-cetak', 'Lifestyle Buku Majalah & Koran (cetak)'),
('Lifestyle', 'Perlengkapan Rumah', 'Furniture', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-furniture', 'Lifestyle Perlengkapan Rumah Furniture'),
('Lifestyle', 'Perlengkapan Rumah', 'Dekorasi', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-dekorasi', 'Lifestyle Perlengkapan Rumah Dekorasi'),
('Lifestyle', 'Perlengkapan Rumah', 'Kamar Mandi & Kamar Tidur', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-kamar-mandi-kamar-tidur', 'Lifestyle Perlengkapan Rumah Kamar Mandi & Kamar Tidur'),
('Lifestyle', 'Perlengkapan Rumah', 'Peralatan Makan & Dapur', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-peralatan-makan-dapur', 'Lifestyle Perlengkapan Rumah Peralatan Makan & Dapur'),
('Lifestyle', 'Perlengkapan Rumah', 'Taman', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-taman', 'Lifestyle Perlengkapan Rumah Taman'),
('Lifestyle', 'Perlengkapan Rumah', 'Alat Pengaman Rumah', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-alat-pengaman-rumah', 'Lifestyle Perlengkapan Rumah Alat Pengaman Rumah'),
('Lifestyle', 'Perlengkapan Rumah', 'Alat Pertukangan', 10, 10, 10, 10, 11.7, 0, 'lifestyle-perlengkapan-rumah-alat-pertukangan', 'Lifestyle Perlengkapan Rumah Alat Pertukangan'),
('Lifestyle', 'Olahraga & Outdoor', 'Alat Olahraga', 10, 10, 10, 10, 11.7, 0, 'lifestyle-olahraga-outdoor-alat-olahraga', 'Lifestyle Olahraga & Outdoor Alat Olahraga'),
('Lifestyle', 'Olahraga & Outdoor', 'Pakaian Olahraga', 10, 10, 10, 10, 11.7, 0, 'lifestyle-olahraga-outdoor-pakaian-olahraga', 'Lifestyle Olahraga & Outdoor Pakaian Olahraga'),
('Lifestyle', 'Olahraga & Outdoor', 'Sepatu Olahraga', 10, 10, 10, 10, 11.7, 0, 'lifestyle-olahraga-outdoor-sepatu-olahraga', 'Lifestyle Olahraga & Outdoor Sepatu Olahraga'),
('Lifestyle', 'Olahraga & Outdoor', 'Aksesoris Olahraga', 10, 10, 10, 10, 11.7, 0, 'lifestyle-olahraga-outdoor-aksesoris-olahraga', 'Lifestyle Olahraga & Outdoor Aksesoris Olahraga'),
('Kategori Lainnya', 'Layanan Digital', 'E-Money', 8.25, 8.25, 8.25, 8.25, 7.7, 1, 'kategori-lainnya-layanan-digital-e-money', 'Kategori Lainnya Layanan Digital E-Money'),
('Kategori Lainnya', 'Gaming', 'Top Up Gaming', 9, 9, 9, 9, 7.2, 1, 'kategori-lainnya-gaming-top-up-gaming', 'Kategori Lainnya Gaming Top Up Gaming'),
('Kategori Lainnya', 'Layanan Digital', 'Belanja (Ritel)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-belanja-ritel', 'Kategori Lainnya Layanan Digital Belanja (Ritel)'),
('Kategori Lainnya', 'Layanan Digital', 'Layanan', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-layanan', 'Kategori Lainnya Layanan Digital Layanan'),
('Kategori Lainnya', 'Layanan Digital', 'Listrik/Gas/Air', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-listrik-gas-air', 'Kategori Lainnya Layanan Digital Listrik/Gas/Air'),
('Kategori Lainnya', 'Layanan Digital', 'Makanan & Minuman (dine-in/takeaway)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-makanan-minuman-dine-in-takeaway', 'Kategori Lainnya Layanan Digital Makanan & Minuman (dine-in/takeaway)'),
('Kategori Lainnya', 'Layanan Digital', 'Shopee (Official, Saldo Iklan)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-shopee-official-saldo-iklan', 'Kategori Lainnya Layanan Digital Shopee (Official, Saldo Iklan)'),
('Kategori Lainnya', 'Layanan Digital', 'Streaming', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-streaming', 'Kategori Lainnya Layanan Digital Streaming'),
('Kategori Lainnya', 'Layanan Digital', 'Telco (Data, Pulsa)', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-telco-data-pulsa', 'Kategori Lainnya Layanan Digital Telco (Data, Pulsa)'),
('Kategori Lainnya', 'Layanan Digital', 'Tiket Event', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-tiket-event', 'Kategori Lainnya Layanan Digital Tiket Event'),
('Kategori Lainnya', 'Layanan Digital', 'Travel & Tour', 9.5, 9.5, 9.5, 9.5, 7.7, 0, 'kategori-lainnya-layanan-digital-travel-tour', 'Kategori Lainnya Layanan Digital Travel & Tour');